
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:eaglebank
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  private-key: classpath:keys/jwt_private.pem
  public-key: classpath:keys/jwt_public.pem
  expiration: 3600000
